version: "3.7"

services:
    spa:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-spa
        container_name: spa
        restart: always
        ports:
            - "4200:80"
    worker:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-worker
        environment:
            MINIO_ENDPOINT: minio
            MINIO_ACCESS_KEY: minio
            MINIO_PORT: 9000
            MINIO_SECRET_KEY: minio123
            MINIO_USE_SSL: "false"
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: redis
        restart: always
        deploy:
            replicas: 5
        depends_on:
            - minio
            - redis
    service:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-service
        container_name: service
        environment:
            MINIO_ENDPOINT: minio
            MINIO_ACCESS_KEY: minio
            MINIO_PORT: 9000
            MINIO_SECRET_KEY: minio123
            MINIO_USE_SSL: false
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: redis
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - minio
            - redis
    minio:
        image: minio/minio
        container_name: minio
        restart: always
        ports:
            - "9000:9000"
            - "9090:9090"
        volumes:
            - minio-data:/data
        environment:
            - MINIO_ACCESS_KEY=minio
            - MINIO_SECRET_KEY=minio123
        command: server /data --console-address ":9090"
    redis:
        image: redis:6.2.6
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes  --requirepass redis

volumes:
    minio-data:
