FROM node:18-alpine AS base

# Install Turbo globally
RUN npm i -g turbo


# Prune the monorepo for the specific app
WORKDIR /app
COPY . .
RUN turbo prune service --docker

# Install dependencies
FROM node:18-alpine AS installer

WORKDIR /app

COPY --from=base /app/out/json/ .
RUN npm ci

# Copy the rest of the application
COPY --from=base /app/out/full/ .



# Final stage for running the application
FROM node:18-alpine AS runner
WORKDIR /app

RUN npm i -g tsx

COPY --from=installer /app .

# Command to start your application
CMD tsx apps/service/src/main.ts
